### PR TITLE
support ATtiny84A, support C++ projects, added include guards

### PR DESCRIPTION
**Pull request by Tekl7**
I have just added support for ATtiny84A MCU.

### CODE REVIEW

**Comment by puuu** [comment]
Thank you for your contribution!
Looks good, did you run the master and slave tests from the example folder?

For my interest: Which framework do you use with this library?

**Comment by Tekl7** [comment]
I have tested only the USI_TWI libraries, not USIWire.
I'm not using any framework with this library (want to save some memory).

**Comment by Tekl7** [comment]
You can look at my fork of AVR SSD1306 Library where I used your library: https://github.com/Tekl7/AVR-SSD1306-Library

**Comment by puuu** [comment]
Thanks! Finally I've merged most of your changes.

I have not merged the C++ changes. IMHO these are C files, you must include them in a C++ within `extern "C"`.

**Pull request closed without merging**
